<?php

declare(strict_types=1);

return [
    'type' => [
        'csv' => 'CSV',
        'xlsx' => 'Excel',
        'pdf' => 'PDF',
    ],
    'shift' => [
        'title' => 'Hours export',
        'sheet_name' => 'Hours',
        'period' => 'Period',
        'timezone' => 'Timezone',
        'footer' => 'Generated by Shiftly • shiftly.alysson-thoaldo.com.br',
        'headings' => [
            'weekday' => 'Day',
            'date' => 'Date',
            'duration' => 'Hours',
        ],
        'summary' => [
            'total' => 'TOTAL',
            'regular' => 'Regular',
            'extra' => 'Extra',
            'missing' => 'Missing',
        ],
    ],
];
