<?php

declare(strict_types=1);

namespace App\Repositories;

use App\Domain\Shift\DTOs\ShiftExportData;
use App\Domain\Shift\Enums\ShiftExportType;
use App\Support\Exports\ShiftExportFormatter;
use Dompdf\Dompdf;
use Dompdf\Options;

final class PdfShiftExportRepository implements ShiftExportRepository
{
    public function type(): ShiftExportType
    {
        return ShiftExportType::Pdf;
    }

    public function labelKey(): string
    {
        return 'exports.type.pdf';
    }

    public function extension(): string
    {
        return 'pdf';
    }

    public function mimeType(): string
    {
        return 'application/pdf';
    }

    public function export(ShiftExportData $data, string $locale): string
    {
        $options = new Options([
            'defaultFont' => 'DejaVu Sans',
            'isRemoteEnabled' => false,
        ]);

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml(view('exports.shifts.pdf', $this->viewData($data, $locale))->render());
        $dompdf->setPaper('A4');
        $dompdf->render();

        return $dompdf->output();
    }

    /**
     * @return array<string, mixed>
     */
    private function viewData(ShiftExportData $data, string $locale): array
    {
        return [
            'documentTitle' => $this->documentTitle($locale),
            'periodLabel' => $this->periodLabel($locale),
            'timezoneLabel' => $this->timezoneLabel($locale),
            'footerLabel' => $this->footerLabel($locale),
            'headings' => ShiftExportFormatter::headings($locale),
            'dayRows' => ShiftExportFormatter::buildDayRows($data, $locale),
            'summaryRows' => $this->summaryRows($data, $locale),
            'startsAt' => $data->startsAt->format('d/m/Y'),
            'endsAt' => $data->endsAt->format('d/m/Y'),
            'timezone' => $data->timezone,
        ];
    }

    /**
     * @return list<array{label: string, duration: string, is_total: bool}>
     */
    private function summaryRows(ShiftExportData $data, string $locale): array
    {
        $rows = ShiftExportFormatter::buildSummaryRows($data, $locale);
        $orderedRows = [];
        $totalRow = null;

        foreach ($rows as $row) {
            if ($row['label'] === 'TOTAL') {
                $totalRow = [
                    ...$row,
                    'is_total' => true,
                ];

                continue;
            }

            $orderedRows[] = [
                ...$row,
                'is_total' => false,
            ];
        }

        if ($totalRow !== null) {
            $orderedRows[] = $totalRow;
        }

        return $orderedRows;
    }

    private function documentTitle(string $locale): string
    {
        return match ($locale) {
            'pt-BR' => 'Exportação de horas',
            default => 'Hours export',
        };
    }

    private function periodLabel(string $locale): string
    {
        return match ($locale) {
            'pt-BR' => 'Período:',
            default => 'Period:',
        };
    }

    private function timezoneLabel(string $locale): string
    {
        return match ($locale) {
            'pt-BR' => 'Fuso:',
            default => 'Timezone:',
        };
    }

    private function footerLabel(string $locale): string
    {
        return match ($locale) {
            'pt-BR' => 'Gerado por Shiftly • shiftly.alysson-thoaldo.com.br',
            default => 'Generated by Shiftly • shiftly.alysson-thoaldo.com.br',
        };
    }
}
